### ISSUE TITLE
Training on KITTI 

### ISSUE THREAD

**Issue by abhigoku10** [SamsungLabs/fcaf3d#12]
@filaPro  hi thanks for opensourcing code base , does this architecture been trained on KITTI , ARGOVerse, Nuscense dataset? if not what changes have to be made for the training on those dataset 
Thanks in advance

**Comment by filaPro** [comment]
Hi @abhigoku10 ,

KITTI and nuScenes are supported in `mmdetection3d`, however all detectors there are either indoor or outdoor. You can check this [issue](https://github.com/open-mmlab/mmdetection3d/issues/1031#issuecomment-962616847). So basically it is not easy to apply `FCAF3D` for outdoor datasets. For example our detection head is multi-scale and sparse 3d, however all detection heads for KITTI are single scale and dense 2d.

**Comment by abhigoku10** [comment]
@filaPro  thanks for the response !!

**Comment by zachluo** [comment]
@filaPro hi, following the discussion, is there any work that has tried to apply voxelnet or pointpillar or others on the Scannet?

**Comment by filaPro** [comment]
Hi @zachluo ,
I am not aware of such works.
