### ISSUE TITLE
Merge with main mmdetection3d repo?

### ISSUE THREAD

**Issue by stanleyshly** [SamsungLabs/fcaf3d#13]
Given this work is modified based on the mmdetection3d repo, are there any plans to update this code to the original mmdetection3d repo?

**Comment by filaPro** [comment]
Hi @stanleyshly,

There is one problem on this way: dependencies of `MinkowskiEngine` and `RotatedIoU`. Both of them require CUDA builds and `MinkowskiEngine` builds for several minutes during installation. I'm not sure if authors of `mmdetection3d` will welcome these dependencies.

Probably, the convolutional backbone and neck can be rewritten with `spconv`, supported in `mmdetection3d` but I'm not ready to analyse it and probably it would be slower than with `MinkowskiEngine`.

**Comment by stanleyshly** [comment]
Thank you your your prompt response, and I do apologize for the slow reply. Thank you for the information, it makes sense, I'll stick with this repo for now.
