### ISSUE TITLE
Alternative Voxel Based Backbones?

### ISSUE THREAD

**Issue by stanleyshly** [SamsungLabs/fcaf3d#14]
Thank you for your wonderful work.
I was wondering, what other voxel backbones were you considering, and why did you select a modified ResNet with spare 3D Convolutions as your backbone?  I wanted to experiment with swapping out backbones, but I'm not sure where to start.

**Comment by filaPro** [comment]
Hi @stanleyshly,

The backbone can probably be replaced even with PointNet (like in VoteNet) or transformer (like in 3DETR). However we only tried voxel-based models from `MinkowskiEngine`. Basically we use `MinkResNet34` following the `GSDN` baseline (from authors of `MinkowskiEngine`). In our paper we also experiment with only first 2 or 3 feature levels of `MinkResNet34` to simplify the model. You can also try `MinkResNet18` or even customize the number of blocks in each feature level by yourself.

**Comment by stanleyshly** [comment]
Thank you for your response once again. To avoid clogging up issues, would it be okay if I contact you through email?

**Comment by filaPro** [comment]
Sure, you are welcome. However it's ok for me to continue questions in this thread.
