### ISSUE TITLE
Can you please share the docker file for CUDA 11.2 

### ISSUE THREAD

**Issue by giangdip2410** [SamsungLabs/fcaf3d#16]
I tried to set up the environment to training FCAF3D model. I followed your guide to set up mmdet & mmdet3d library with CUDA 11.2, but the last step for installing MinkowskiEngine, I couldn't install this library with CUDA 11.2 . If anybody have already done for training FCAF3D with CUDA 11.2, please share with me your docker. Thank you so much.

**Comment by filaPro** [comment]
Hi @giangdip2410 ,

Can you share the error logs? If it is a problem of MinkowskiEngine you can ask in their repo?

**Comment by giangdip2410** [comment]
Hi @filaPro , thank you for your suggestion. I just found a docker 11.1 to train fcaf3d model at : https://hub.docker.com/r/god2000sus/mmdet3dtrial. It solved my issue.
