### ISSUE TITLE
Nothing happened when I visualized my latest.pth

### ISSUE THREAD

**Issue by joshiaLee** [SamsungLabs/fcaf3d#17]
Thank you for your Greak work! 
I followed your dockerfile and everything was well-done.
training and evaluation were great.
but when i visualized my latest.pth
there is nothing happened
it seemed like processing my checkpoint file but i cannot understand what was done(any file didn't be produced).

should i additionally install more program to visualize something?
here is my problem.

`root@0dea488ce090:/mmdetection3d# python tools/test.py configs/fcaf3d/fcaf3d_sunrgbd-3d-10class.py     /mmdetection3d/work_dirs/fcaf3d_sunrgbd-3d-10class/latest.pth  --show     --show-dir /mmdetection3d/work_dirs/fcaf3d_sunrgbd-3d-10class
Use load_from_local loader
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 5050/5050, 8.0 task/s, elapsed: 632s, ETA:     0sroot@0dea488ce090:/mmdetection3d#  
root@0dea488ce090:/mmdetection3d# `

**Comment by filaPro** [comment]
Hi @joshiaLee,

As I remember after this command there should be generated some `.obj` files in `/mmdetection3d/work_dirs/fcaf3d_sunrgbd-3d-10class` and you should be able to open them in `MeshLab` to get visualizations like in our paper. Are there these `.obj` files in your case? If not, I will check it.

**Comment by joshiaLee** [comment]
thanks for your quick reply.
sadly there's no any file in my `/mmdetection3d/work_dirs/fcaf3d_sunrgbd-3d-10class` 
l had done so many times but nothing haha

**Comment by filaPro** [comment]
Can you please try the same command but with `--eval mAP`?

**Comment by joshiaLee** [comment]
Thank you so much!
finally i got three object files( gt.obj points.obj pred.obj )
