### ISSUE TITLE
how should I understand results?

### ISSUE THREAD

**Issue by joshiaLee** [SamsungLabs/fcaf3d#18]
I made 3 .obj files through your model checkfile. and I visualized that in mashlab.
(left is a gt and right is a predition) but while gt has only 2boxes , predtion had so many bounding boxes (looks like many anchor boxes)
how should I understand the results? please explain that to me
![Screenshot from 2022-02-18 22-38-09](https://user-images.githubusercontent.com/93809073/154694417-5a122fb6-5d65-442a-901d-37748f90482e.png)

**Comment by filaPro** [comment]
Have you set `score_thr=0.2` in config file?

Btw, you can open `gt`, `pred` and `points` together 
![Screenshot from 2022-02-18 17-03-07](https://user-images.githubusercontent.com/6030962/154697189-b9972e9b-2432-44ad-8f1b-0bee42cc74e8.png)
and even make them colored in your right panel.

**Comment by joshiaLee** [comment]
Oh I missed it!
Thanks
