### ISSUE TITLE
I'd like to detect small objects

### ISSUE THREAD

**Issue by joshiaLee** [SamsungLabs/fcaf3d#20]
sorry for bothering you.
I have been studying this project and I have some questions.

1. I'd like to detect small objects like cups, lamps and such things.
when i trained and evaluated sunrgbd datas including those. it reported good results. like below 
![Screenshot_2022-02-22_02-04-18](https://user-images.githubusercontent.com/93809073/154999583-0151c197-b82c-46a0-91be-4298d6131361.png)
but when I visualized three object files, ground truth and prediction both ignored all the small objects that I included.
they only displayed relatively big objects like table,chair,bed,desk (I set score_thr = 0.1)
![Screenshot_2022-02-22_02-13-31](https://user-images.githubusercontent.com/93809073/155001027-a60081ec-784e-4ab0-ab69-a80eacf4d300.png)
how can I modify to obtain the things desired?

2. how can I feed my own datas?
finally I'd like to train and predict my own datas(i.g apple.)
I'm likely to know how to train and evaluate and visualize my datas (just adding my datas to sunrgbd pipelines.)
my question is that If i train well, how could I feed my real time a single data to model in order to predict centroids or bounding boxes.
(format might be .ply or .pcd)
is there any commands to do this work?

**Comment by filaPro** [comment]
Feel free to ask any questions :)

1. It's hard to guess what is the problem exactly. First you need to list the predicted and ground truth `cup` objects [here](https://github.com/SamsungLabs/fcaf3d/blob/master/mmdet3d/datasets/custom_3d.py#L262-L263). Then you can debug what is going on with them in the visualization [function](https://github.com/SamsungLabs/fcaf3d/blob/master/mmdet3d/datasets/sunrgbd_dataset.py#L179). Btw, you can set `[100:101]` [here](https://github.com/SamsungLabs/fcaf3d/blob/master/mmdet3d/datasets/custom_3d.py#L81) to debug on the single scene and not to wait the whole dataset.

2. I don't quite understand the question. Do you want to run the trained model on a single scene? Actually you can see [demo](https://github.com/SamsungLabs/fcaf3d/tree/master/demo) scripts from original `mmdeteciton3d`, e.g. `pcd_demo.py`.
,

**Comment by joshiaLee** [comment]
1. Okay I'll try it
2. Yeah, that's what I mean 
Thanks!!

**Comment by joshiaLee** [comment]
finally i solved the problem during debugging
https://github.com/SamsungLabs/fcaf3d/blob/5cd7ea458c194010cb35f3d999c9dde900eb2e7d/tools/data_converter/sunrgbd_data_utils.py#L74
you can replacee the classes you want
Thanks
