### ISSUE TITLE
I encounter the error KeyError: 'gt_bboxes_3d' when i try to use visualize_results.py

### ISSUE THREAD

**Issue by acasium** [SamsungLabs/fcaf3d#21]
The command i used:
python tools/misc/visualize_results.py configs/fcaf3d/fcaf3d_sunrgbd-3d-10class.py --result data/sunrgbd/sunrgbd_infos_val.pkl --show-dir workdir

The result i get:
Traceback (most recent call last):
  File "tools/misc/visualize_results.py", line 48, in <module>
    main()
  File "tools/misc/visualize_results.py", line 40, in main
    dataset.show(results, args.show_dir)  # use default pipeline
  File "/home/intern/Downloads/Samsunglabs/fcaf3d/mmdet3d/datasets/sunrgbd_dataset.py", line 207, in show
    pred_bboxes = result['boxes_3d']
KeyError: 'boxes_3d'

**Comment by filaPro** [comment]
Hi @acasium ,

We modified some `mmdetection3d` codes not carefully enough, so some scripts may not work. Can you please try visualization as pointed in the relevant section of our `readme`?

**Comment by acasium** [comment]
Hi @filaPro 
Thanks for your time. I will do it.
