### ISSUE TITLE
I run the trained model on a single data and encountered buffer size issue

### ISSUE THREAD

**Issue by joshiaLee** [SamsungLabs/fcaf3d#22]
I want to run the trained model on my own data.
I followed the pcd_demo.py requirments.

`(base) root@01d3ccee40b8:/mmdetection3d/demo# python pcd_demo.py /mmdetection3d/demo/apple1.pcd /mmdetection3d/configs/fcaf3d/fcaf3d_sunrgbd-3d-10class.py /mmdetection3d/work_dirs/fcaf3d_sunrgbd-3d-10class/latest.pth --score-thr 0.1 --show
Use load_from_local loader
Traceback (most recent call last):
  File "pcd_demo.py", line 41, in <module>
    main()
  File "pcd_demo.py", line 28, in main
    result, data = inference_detector(model, args.pcd)
  File "/mmdetection3d/mmdet3d/apis/inference.py", line 104, in inference_detector
    data = test_pipeline(data)
  File "/opt/conda/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 415, in __call__
    points = self._load_points(pts_filename)
  File "/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 391, in _load_points
    points = np.frombuffer(pts_bytes, dtype=np.float32)
ValueError: buffer size must be a multiple of element size`
I searched in Google but they didn't deal with pointcloud and i didnt get a useful advice.

**Comment by filaPro** [comment]
Looks like this `.pcd` file should be an `np.array` of shape `(N, 6)` saved to binary by `np.save`. Have you done it like this?

**Comment by joshiaLee** [comment]
No,
I made my data using the Intel_realsense application it produced .ply file 
and I just converted that file to pcd file like this
`import open3d as o3d
pcd = o3d.io.read_point_cloud("apple1.ply")
o3d.io.write_point_cloud("apple1.pcd", pcd)`
how should I save it by np.save?

**Comment by joshiaLee** [comment]
ahha
its shape was (N,4) 
Thanks, I'll try again
