### ISSUE TITLE
how can I increase small objects'mAP?

### ISSUE THREAD

**Issue by joshiaLee** [SamsungLabs/fcaf3d#23]
Hi
I selected 10 small objects in SUNRGBD and I made those trained in this model.
but, result showed only 0.1mAP( learning_rate = 0.001, epoch = 12, Objects were cup,bottle,bowl,book etc)
I guess this model was designed for big objects not small things, right?
then, how can I increase small objects' mAP? are there any parameters to do that?

**Comment by joshiaLee** [comment]
Thank you sooooo much!

**Comment by joshiaLee** [comment]
![bandicam 2022-02-26 00-42-18-603](https://user-images.githubusercontent.com/93809073/155744432-e1666d8b-692d-46c1-9609-ed8c037a61fc.jpg)
I'm compused a little
feature levels you meaned is n_scores=2? or n_reg_outs=6?
does what both mean?

**Comment by filaPro** [comment]
[Here](https://github.com/SamsungLabs/fcaf3d/blob/master/configs/fcaf3d/fcaf3d_2scales_scannet-3d-18class.py) we decrease `n_outs`, `in_channels` and `n_scales`.

**Comment by joshiaLee** [comment]
I got it 
Thank you!
