### ISSUE TITLE
mAP depending on score_thr

### ISSUE THREAD

**Issue by joshiaLee** [SamsungLabs/fcaf3d#25]
Hi! me again
I've designed my own detector for persimmon Thanks to your advice.
it's mAP was 0.7 wow! your model is amazing.
btw, when I set score_thr =0.1, it decreased upto 0.58
if I set score_thr=0.3(because 0.3 is higher than 0.25 IOU), it would be right.
but I set only 0.1
why this phenomenon occured? and which mAP is real?

**Comment by filaPro** [comment]
Don't quite understand how `score_thr=0.3` is connected with IoU threshold `=0.25`.
Generally in 2d or 3d detection mAP is getting better with decreasing  `score_thr`. However this growth is usually neglible after `score_thr=0.05`.

**Comment by joshiaLee** [comment]
Ahha thanks
