### ISSUE TITLE
How does demo predict gravity direction without calibration data?

### ISSUE THREAD

**Issue by joshiaLee** [SamsungLabs/fcaf3d#26]
Hi
I know that calibration information is very important in training.
but pcd_demo.py only required pcd file(binary format). I searched that format and it just contained depth data without calibration.
I wonder how this model predicted the gravity direction without calibration data.

**Comment by filaPro** [comment]
Point cloud is made from single depth image for SUN RGB-D, and from multiple depth images for ScanNet and S3DIS. However for all datasets the point clouds are rotated to match the gravity direction by the dataset creators. We train and test our models only on such aligned point clouds. So for your own data you basically should make the rotation somehow on your side.

**Comment by joshiaLee** [comment]
Thank you for the perfect answer.
