### ISSUE TITLE
another version fcaf3d

### ISSUE THREAD

**Issue by LXie502** [SamsungLabs/fcaf3d#28]
hello, Danila, very glad to contact you,  writing to ask you a question, thanks for you help.
you have done a grate job about "FCAF3D: Fully Convolutional Anchor-Free 3D Object Detection" and given a released code, 
I just want to know do you have another version source code which is not based on mmdetection3d, mmdetection3d is hard to modification, so, could you release a code which is easy to apply,  look for you reply, thanks very much.

**Comment by filaPro** [comment]
Hi @LXie502 ,

No, we don't have another version of source code. However in my opinion `mmdetection3d` (and other `open-mmlab` projects) is designed perfectly for your own research and modifications. `FCAF3D` code is mainly located in 3 files listed in our `readme`,  so you can start exploration from this point.

**Comment by LXie502** [comment]
thanks, because I have to recompose the code with another task, it was a multitask method, i just want the main 3 files, but it was hard to stripping，dou you have any suggestion about have to quick use your code without mmdetection3d.

**Comment by filaPro** [comment]
I think it will be not easy :( As least `FCAF3D` requires some `cuda` ops including `MinkowskiEngine`, differentiable `rotated_iou` and 3d `nms`.
