### ISSUE TITLE
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1603729009598/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8

### ISSUE THREAD

**Issue by PengboLi1998** [SamsungLabs/fcaf3d#29]
hello，when i use your s3dis pretrained model to test,it throws the following errors.Could you please help me ?
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1603729009598/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8

**Comment by filaPro** [comment]
Looks like your `pytorch + cuda` installation is not good. Can you please try with our `Dockerfile`? Also please attach the output of `python mmdet3d/utils/collect_env.py` and full traceback of the error from python.
