### ISSUE TITLE
visualization question

### ISSUE THREAD

**Issue by PengboLi1998** [SamsungLabs/fcaf3d#31]
![image](https://user-images.githubusercontent.com/102470052/165032004-233c57f7-4c44-4c0b-9e89-040eedca43bc.png)
hello,I have generate the .obj ，but，when i open it with meshlab .It shows like the picture.

**Comment by PengboLi1998** [comment]
it does not like your paper

**Comment by filaPro** [comment]
Hi @PengboLi1998 ,

Did you set `score_thr` in a config file to `0.2` as we recommend in `readme`? You can also open point cloud, `gt` and `pred` in the same meshlab project and make box faces transparent, edges thicker and colored.

**Comment by PengboLi1998** [comment]
yes,i have set the score_thr=0.2.I will use meshlab to try your method again.By the way,i download your s3dis pretrained model to test and show .

**Comment by PengboLi1998** [comment]
Normally,shoud import mesh or open project in meshlab,your pred .obj is only the predict frame or original point cloud with predict frame?

**Comment by filaPro** [comment]
Meshlab project should be like this. I have just checked now for `Area_5_office_32` from S3DIS.

![Screenshot from 2022-04-25 11-27-33](https://user-images.githubusercontent.com/6030962/165040738-9c9b32df-6fbe-4b1a-b755-67da85044696.png)

**Comment by PengboLi1998** [comment]
OK， I have solved it. Thank you very much

**Comment by ahelamin** [comment]
How did you solve this problem? I have similar issue with sunrgbd dataset
