### ISSUE TITLE
train.py: error: unrecognized arguments: --load-from fully_conv_s3dis.pth

### ISSUE THREAD

**Issue by PengboLi1998** [SamsungLabs/fcaf3d#32]
Hi，it is me again.I want to use the your offered pretrained model of s3dis to train my own dataset.So I need to use the 'load-from' to fine tune the model.But when i use the 'load-from',it throws the error:
train.py: error: unrecognized arguments: --load-from fully_conv_s3dis.pth
How to deal with this situation?
Thank you very much!

**Comment by filaPro** [comment]
I think you can set `load_from` argument directly in config file, e.g. [here](https://github.com/SamsungLabs/fcaf3d/blob/master/configs/fcaf3d/fcaf3d.py#L46).
