### ISSUE TITLE
Can MinkowskiGenerativeConvolutionTranspose from fcaf3d_neck_with_head.py replaced?

### ISSUE THREAD

**Issue by YJYJLee** [SamsungLabs/fcaf3d#33]
Hi, thank you for the great work!

I noticed that the code uses MinkowskiEngine as the backend. I am trying to replace the backend with Spconv, which is one of the different sparse convolution libraries for a research purpose.

I found out that fcaf3d is using MinkowkiGenerativeConvolutionTranspose in fcaf3d_neck_with_head.py. I am not sure how I could replace that function with spconv apis. 
How is MinkowkiGenerativeConvolutionTranspose different from MinkowskiConvolutionTranspose? The documentation says it produces new coordinates, but is this necessary, or can be replaced with MinkowskiConvolutionTranspose?
If not, is there any workaround for this?

Thanks!

**Comment by filaPro** [comment]
Hi @YJYJLee,

You can replace `MinkowskiGenerativeConvolutionTranspose` with `MinkowskiConvolutionTranspose` and also remove `MinkowskiPruning`. The model will be significantly faster e.g. ~1.5 times, but mAP will be ~10% worth.

About `spconv`, they have `SparseConv3D` and `SubMConv3D` and this second one expands the number of points in the output tensor. You can use `SparseConvTranspose3D` + `SubMConv3D`. I think it will have the same behavior.

**Comment by YJYJLee** [comment]
@filaPro Thank you so much for the fast reply!

I changed `MinkowskiGenerativeConvolutionTranspose` with `SparseConvTranspose3D`+`SubMConv3D` as you mentioned :)

However, I want to change backend with `spconv` without loss in mAP and I am stuck with how I could deal with `MinkowskiPruning`.
Do you have any idea on how to get `decomposition_permutations`?

**Comment by filaPro** [comment]
Actually `decomposition_permutations` is just the separating the tensor by the batch index. `spconv` also has something like:
```python
for i in range(batch_size):
    y = x.indices[:, 0] == i
```

**Comment by FabianSchuetze** [comment]
Did you had any luck replacing Minkowski with spconv, @YJYJLee ? Building spconv is much easier and faster for me than Minkowski, so I'd be glad to receive some indications how to do that.

**Comment by cama36** [comment]
> Did you had any luck replacing Minkowski with spconv, @YJYJLee ? Building spconv is much easier and faster for me than Minkowski, so I'd be glad to receive some indications how to do that.

Did you replace it successfully?
