### ISSUE TITLE
output all predict bbox coordinate position

### ISSUE THREAD

**Issue by PengboLi1998** [SamsungLabs/fcaf3d#34]
Hello,I successfully run your code,but I want to output all predict bbox coordinate position.I have tried print the bbox_list in single_stage_mono3d.py,but when i run the tools/test.py ,I found it did not call the single_stage_mono3d.py.Could you please help me ?

**Comment by filaPro** [comment]
Hi @PengboLi1998 ,

As you use `fcaf3d` you should try to print boxes in [SingleStageSparse3DDetector](https://github.com/SamsungLabs/fcaf3d/blob/master/configs/fcaf3d/fcaf3d.py#L4).

**Comment by PengboLi1998** [comment]
Hello，I have printed the predicted bbox coordinate ,but I found the coordinate system has changed from the original input point cloud.And what should I do to keep same with original input point cloud coordinate system.
