### ISSUE TITLE
Concatenate different feature levels to one level before passing data to the heads

### ISSUE THREAD

**Issue by FabianSchuetze** [SamsungLabs/fcaf3d#43]
Thanks for the wonderful work! I learned a lot from reading the paper and going over the code. 

I was wondering whether there would be a chance to use an FPN to produce one feature map of size WxHxC instead of going over the different levels for each box prediction? I guess that would be done here: https://github.com/SamsungLabs/fcaf3d/blob/ad5985dd054fe70452da9cd27354f39150d12114/mmdet3d/models/dense_heads/fcaf3d_neck_with_head.py#L104 or ? To the Minkowski convolution permit the transformation from a spare set to a feature image of fixed height and width? Do you have any idea what the impact on the accuracy would be?

**Comment by filaPro** [comment]
Hi @FabianSchuetze ,

Don't quite understand your question. All tensors in fcaf3d are sparse and 3-dimensional (W x L x H x C). You can somehow use pooling or strided convolutions to remove one of dimensions and make the shape W x H x C. But why would you do this? To work with BEV projection? To make dense tensor from sparse you can use `.dense()` method.

**Comment by FabianSchuetze** [comment]
Thanks, @filaPro  for your kind and detailed response. 

Indeed, you are right: I would like to try a prediction from a kind-of-BEV. Making the predictions on different level is very interesting, and out of curiosity I would like to do a CenterPoint-type prediction from a single layer as ablation. I thought of upsamling the spare tensors to a common resolution and then doing a max pooling over them. Do you have an idea how I could to that. 

I tried to call the `dense` method on the `out` matrix but this fails because some coordinates are negative and I have to provide a `min_coordinate` argument to the `dense` function. Do you have an idea which arguments I could use?
