### ISSUE TITLE
Generalization of FCAF3D

### ISSUE THREAD

**Issue by Eaphan** [SamsungLabs/fcaf3d#45]
Thanks for your sharing. The FCAF3D is concise and effective. Have you ever tried to apply it to outdoor scenes?

**Comment by filaPro** [comment]
Hi @Eaphan,
No, we didn't try. FCAF3D is mainly about its novel head (including assigner), which seems not very relevant to outdoor detectors with mainly 2D (BEV) head.

**Comment by Eaphan** [comment]
Thanks for your reply. Maybe the general scheme of the proposed FCAF3D is also effective for outdoor scenes while the OBB parametrization is designed for objects with an ambiguous heading angle.
