### ISSUE TITLE
FCAF3D evaluation result mAP question

### ISSUE THREAD

**Issue by wenchened** [SamsungLabs/fcaf3d#48]
Hi ! Thanks for you wonderful work! I have learned a lot from your job，but i have a simple question
For evaluation，you say you report the best metrics accross 5*5 trails，do you mean
1、the best mAP0.25 and mAP0.5 in your paper is come from the same pth and the same test result or
2、select the best mAP0.25 and mAP0.5  respectively from the 25 results，they are not come from one result

**Comment by filaPro** [comment]
Hi @wenchened ,
Your second option is correct.

**Comment by wenchened** [comment]
Thank you very much！
